[store]
    [store.streaming]
        pluginFileNames = [ # if we have any plugins, we are streaming
            "file", # name of the .so file we are loading as a plugin; don't include the .so file extension
        ]

[streaming]
    [streaming.file] # a list of plugin-specific parameters, mapped to their pluginFileName
        # pluginDir is required for every plugin and will default to a directory located at store/streaming/plugin/plugins with the same name as the plugin
        pluginDir = "path to the directory with the plugins"
        keys = ["list", "of", "store", "keys", "we", "want", "to", "expose", "for", "this", "streaming", "service"]
        writeDir = "path to the write directory"
        prefix = "optional prefix to prepend to the generated file names"
